릴리즈 버전 소팅 기능 향상

diff --git a/upgrade-gitlab-ce b/upgrade-gitlab-ce
--- a/upgrade-gitlab-ce
+++ b/upgrade-gitlab-ce
@@ -4,6 +4,8 @@ use_local_versions=0
 extract_versions_only=0
 auto_restart_enabled=no
 
+PAGE_SIZE=${PAGE_SIZE:-10}
+
 if [ "$1" == "--help" -o "$1" == "help" ]; then
     echo "usage: $0 [option|FILE]"
     echo -e '\n\e[0;1mOPTIONS\e[m'
@@ -13,6 +15,7 @@ if [ "$1" == "--help" -o "$1" == "help" ]; then
     echo -en "FILE\t\tusing provided file with already ASC sorted contents"
     echo -e '\n\e[0;1mENV VALUES\e[m'
     echo -e "TARGET_URL\tA simple connection test for your GitLab server."
+    echo -e "PAGE_SIZE=10\thow many spolling amount each page."
     exit 0
 elif [ -f "$1" ]; then
     echo "using $1 file to take effect reducing time about sorting version tags"
@@ -21,6 +24,7 @@ elif [ -f "$1" ]; then
         echo '' >> "$1"
     fi
 
+    cat "$1" | grep -viE '(rc|nightly|latest)' | tee "$1" > /dev/null
     requirements=$(cat "$1" | grep -cE '^[0-9]+\.[0-9]+\.[0-9]+-ce\.[0-9]+$')
     total=$(cat "$1" | wc -l)
     if [ $requirements -ne $total ]; then
@@ -95,90 +99,91 @@ draw_progress() {
 }
 
 if [ $use_local_versions -ne 1 ]; then
-  PAGE_SIZE=100
-  TAGS_URL="https://hub.docker.com/v2/repositories/gitlab/gitlab-ce/tags/?page_size=$PAGE_SIZE"
-  
-  # 1. 첫 페이지 요청
-  RESPONSE=$(curl -sL "$TAGS_URL")
-  TOTAL_COUNT=$(echo "$RESPONSE" | jq '.count')
-  
-  # 2. 전체 페이지 수 계산
-  TOTAL_PAGES=$(( (TOTAL_COUNT + PAGE_SIZE - 1) / PAGE_SIZE ))
-  
-  ALL_TAGS=()
+    TAGS_URL="https://hub.docker.com/v2/repositories/gitlab/gitlab-ce/tags/?page_size=$PAGE_SIZE"
 
-  if [ $extract_versions_only -ne 1 ]; then
-    echo "NOTE: Please run $0 --extract to reduce running time."
-    echo -e "\tmore infomation please enter $0 --help command"
-  fi
-
-  echo "Spolling GitLab-CE container tags... location: $TAGS_URL"
-  while [ -n "$TAGS_URL" ]; do
+    # 1. 첫 페이지 요청
     RESPONSE=$(curl -sL "$TAGS_URL")
-    TAGS=$(echo "$RESPONSE" | jq -r '.results[].name')
-    if [ -z "$TAGS" ]; then
-      break  # 더 이상 태그 없음
-    else
-        CURRENT_PAGE=$(echo "$TAGS_URL" | grep -oP 'page=\K[0-9]+' || echo 1)
-        draw_progress $CURRENT_PAGE $TOTAL_PAGES 'Querying GitLab Releases' 'Page'
-    fi
-    ALL_TAGS+=($TAGS)
-    TAGS_URL=$(echo "$RESPONSE" | jq -r '.next')
-  done
+    TOTAL_COUNT=$(echo "$RESPONSE" | jq '.count')
 
-  echo -e "\nSorting ASC GitLab-CE released tags..."
-  FILTERED_TAGS=()
-  for tag in "${ALL_TAGS[@]}"; do
-    [[ "$tag" =~ rc|nightly|latest ]] && continue
-    FILTERED_TAGS+=("$tag")
-  done
+    # 2. 전체 페이지 수 계산
+    TOTAL_PAGES=$(( (TOTAL_COUNT + PAGE_SIZE - 1) / PAGE_SIZE ))
 
-  # 버전 정렬
-  if [ $extract_versions_only -ne 1 ]; then
-    for ((i=0; i<${#FILTERED_TAGS[@]}-1; i++)); do
-      draw_progress $(($i+1)) ${#FILTERED_TAGS[@]} 'Sorting versions' 'Item'
+    ALL_TAGS=()
 
-      for ((j=i+1; j<${#FILTERED_TAGS[@]}; j++)); do
-          # 숫자 기준 비교
-          if [[ "$(printf '%s\n%s\n' "${FILTERED_TAGS[i]}" "${FILTERED_TAGS[j]}" | sort -V | head -n1)" == "${FILTERED_TAGS[j]}" ]]; then
-              # swap
-              tmp=${FILTERED_TAGS[i]}
-              FILTERED_TAGS[i]=${FILTERED_TAGS[j]}
-              FILTERED_TAGS[j]=$tmp
-          fi
-      done
-    done
-  else
-      echo 'note: successfully export gitlab-ce released tags. please sort ASC order these tags. location: /tmp/gitlab-released-tags.txt'
-      echo "${FILTERED_TAGS[@]}" | tr ' ' '\n' > /tmp/gitlab-released-tags.txt
-      exit 0
-  fi
-
-  ALL_TAGS=$FILTERED_TAGS
-else
-  cat "$1" | tr ' ' '\n' | tee "$1" > /dev/null
-  RAW_TAGS_N=$(cat "$1" | grep -viE '(rc|nightly|latest)')
-  count=1
-  mapfile -t RAW_TAGS <<< "$RAW_TAGS_N"
-
-  for idx in "${!RAW_TAGS[@]}"; do
-    tag="${RAW_TAGS[$idx]}"
-    draw_progress $count ${#RAW_TAGS[@]} "Importing provided contents" 'Item'
-
-    # 배열에 추가
-    ALL_TAGS+=("$tag")
-    count=$((count + 1))
-
-    # 첫 번째 비교
-    if [ $((idx + 1)) -lt ${#RAW_TAGS[@]} ]; then
-        next_tag="${RAW_TAGS[$((idx + 1))]}"
-        first=$(printf '%s\n%s\n' "$tag" "$next_tag" | sort -V | head -n1)
-        if ! [[ "$first" == "$tag" ]]; then
-            echo -e "\nerror: tags are NOT in ASC order: $tag > $next_tag" >&2
-            exit 1
+    echo "Spolling GitLab-CE container tags... location: $TAGS_URL"
+    while [ -n "$TAGS_URL" ]; do
+        RESPONSE=$(curl -sL "$TAGS_URL")
+        TAGS=$(echo "$RESPONSE" | jq -r '.results[].name')
+        if [ -z "$TAGS" ]; then
+          break  # 더 이상 태그 없음
+        else
+            CURRENT_PAGE=$(echo "$TAGS_URL" | grep -oP 'page=\K[0-9]+' || echo 1)
+            draw_progress $CURRENT_PAGE $TOTAL_PAGES 'Querying GitLab Releases' 'Page'
         fi
+        ALL_TAGS+=($TAGS)
+        TAGS_URL=$(echo "$RESPONSE" | jq -r '.next')
+    done
+
+    echo -e "\nSorting ASC GitLab-CE released tags..."
+
+    # 버전 정렬
+    printf '%s\n' "${ALL_TAGS[@]}" > /tmp/gitlab-parsed.log
+    cat /tmp/gitlab-parsed.log | tr ' ' '\n' | tee /tmp/gitlab-parsed.log > /dev/null
+
+    RAW_TAGS_N=$(cat /tmp/gitlab-parsed.log | sort -V | grep -viE '(rc|nightly|latest)')
+    count=1
+    mapfile -t RAW_TAGS <<< "$RAW_TAGS_N"
+
+    ALL_TAGS=()
+    for idx in "${!RAW_TAGS[@]}"; do
+        tag="${RAW_TAGS[$idx]}"
+        draw_progress $count ${#RAW_TAGS[@]} "Exporting provided contents" 'Item'
+
+        # 배열에 추가
+        ALL_TAGS+=("$tag")
+        count=$((count + 1))
+
+        # 첫 번째 비교
+        if [ $((idx + 1)) -lt ${#RAW_TAGS[@]} ]; then
+            next_tag="${RAW_TAGS[$((idx + 1))]}"
+            first=$(printf '%s\n%s\n' "$tag" "$next_tag" | sort -V | head -n1)
+            if ! [[ "$first" == "$tag" ]]; then
+                echo -e "\nerror: tags are NOT in ASC order: $tag > $next_tag" >&2
+                exit 1
+            fi
+        fi
+    done
+    rm /tmp/gitlab-parsed.log 2> /dev/null
+
+    if [ $extract_versions_only -eq 1 ]; then
+        echo -e '\nnote: successfully export gitlab-ce released tags. please sort ASC order these tags. location: /tmp/gitlab-released-tags.txt'
+        echo "${ALL_TAGS[@]}" | tr ' ' '\n' > /tmp/gitlab-released-tags.txt
+        exit 0
     fi
-  done
+else
+    cat "$1" | tr ' ' '\n' | tee "$1" > /dev/null
+    RAW_TAGS_N=$(cat "$1" | sort -V | grep -viE '(rc|nightly|latest)')
+    count=1
+    mapfile -t RAW_TAGS <<< "$RAW_TAGS_N"
+
+    for idx in "${!RAW_TAGS[@]}"; do
+        tag="${RAW_TAGS[$idx]}"
+        draw_progress $count ${#RAW_TAGS[@]} "Importing provided contents" 'Item'
+
+        # 배열에 추가
+        ALL_TAGS+=("$tag")
+        count=$((count + 1))
+
+        # 첫 번째 비교
+        if [ $((idx + 1)) -lt ${#RAW_TAGS[@]} ]; then
+            next_tag="${RAW_TAGS[$((idx + 1))]}"
+            first=$(printf '%s\n%s\n' "$tag" "$next_tag" | sort -V | head -n1)
+            if ! [[ "$first" == "$tag" ]]; then
+                echo -e "\nerror: tags are NOT in ASC order: $tag > $next_tag" >&2
+                exit 1
+            fi
+        fi
+    done
 fi
 
 # 1. 현재 버전 이후만 필터링
@@ -186,7 +191,7 @@ UPDATABLE_TAGS=()
 
 count=1
 for idx in "${!ALL_TAGS[@]}"; do
-    tag="${RAW_TAGS[$idx]}"
+    tag="${ALL_TAGS[$idx]}"
     draw_progress $count ${#ALL_TAGS[@]} "Listing tags after $CURRENT_VERSION" 'Item'
 
     # 현재 버전보다 최신이면 배열에 추가
